;Include this in your own platform.ini file along with your other environments

[env:native]
platform = native
build_src_filter = +<main.cpp> +<HAL_SIL.cpp> +<native_main.cpp>
lib_deps = 
build_flags = -lws2_32 -mconsole

